from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='books.index'),
    path('list_books/', views.list_books, name='books.list_books'),
    path('<int:bookId>/', views.viewbook, name='books.view_one_book'),
    path('aboutus/', views.aboutus, name='books.aboutus'),
       path('html5/links', views.links, name='books.links'),
       path('html5/text/formatting', views.formatting, name='books.formatting'),
       path('html5/listing', views.listing, name='books.listing'),
       path('html5/tables', views.tables, name='books.tables'),
       path('search', views.search, name='books.search'),
      path('simple/query', views.simple_query, name='books.simple_query'),
path('complex/query', views.complex_query, name='books.complex_query'),
path('lab8/task1', views.lab8_task1, name='books.lab8_task1'),
path('lab8/task2', views.lab8_task2, name='books.lab8_task2'),
path('lab8/task3', views.lab8_task3, name='books.lab8_task3'),
path('lab8/task4', views.lab8_task4, name='books.lab8_task4'),
path('lab8/task5', views.lab8_task5, name='books.lab8_task5'),
path(
    'lab8/students-per-city',
    views.students_per_city,
    name='books.students_per_city'
),
path('lab9/task1', views.lab9_task1, name='books.lab9_task1'),
path('lab9/task2', views.lab9_task2, name='books.lab9_task2'),
path('lab9/task3', views.lab9_task3, name='books.lab9_task3'),
path('lab9/task4', views.lab9_task4, name='books.lab9_task4'),
path('lab9_part1/listbooks', views.lab10_part1_listbooks, name='books.lab10_part1_listbooks'),
path('lab9_part1/addbook', views.lab10_part1_addbook, name='books.lab10_part1_addbook'),
path('lab9_part1/editbook/<int:id>', views.lab10_part1_editbook, name='books.lab10_part1_editbook'),
path('lab9_part1/deletebook/<int:id>', views.lab10_part1_deletebook, name='books.lab10_part1_deletebook'),
path('lab9_part2/listbooks', views.lab10_part2_listbooks, name='books.lab10_part2_listbooks'),
path('lab9_part2/addbook', views.lab10_part2_addbook, name='books.lab10_part2_addbook'),
path('lab9_part2/editbook/<int:id>', views.lab10_part2_editbook, name='books.lab10_part2_editbook'),
path('lab9_part2/deletebook/<int:id>', views.lab10_part2_deletebook, name='books.lab10_part2_deletebook'),
path('lab11/task1/students', views.lab11_task1_list, name='books.lab11_task1_list'),
path('lab11/task1/students/add', views.lab11_task1_add, name='books.lab11_task1_add'),
path('lab11/task1/students/edit/<int:id>', views.lab11_task1_edit, name='books.lab11_task1_edit'),
path('lab11/task1/students/delete/<int:id>', views.lab11_task1_delete, name='books.lab11_task1_delete'),
path('lab11/task2/students', views.lab11_task2_list, name='books.lab11_task2_list'),
path('lab11/task2/students/add', views.lab11_task2_add, name='books.lab11_task2_add'),
path('lab11/task2/students/edit/<int:id>', views.lab11_task2_edit, name='books.lab11_task2_edit'),
path('lab11/task2/students/delete/<int:id>', views.lab11_task2_delete, name='books.lab11_task2_delete'),
path('lab11/task3/products', views.lab11_task3_list, name='books.lab11_task3_list'),
path('lab11/task3/products/add', views.lab11_task3_add, name='books.lab11_task3_add'),
path('lab11/task3/products/edit/<int:id>', views.lab11_task3_edit, name='books.lab11_task3_edit'),
path('lab11/task3/products/delete/<int:id>', views.lab11_task3_delete, name='books.lab11_task3_delete'),
]